(function(){
function store(l){try{localStorage.setItem('fds-lang',l)}catch(e){}}
document.querySelectorAll('[data-setlang]').forEach(function(a){a.addEventListener('click',function(){store(a.getAttribute('data-setlang'))})});
var hb=document.getElementById('hamburger'),mm=document.getElementById('mobileMenu');
function setMenu(o){hb.classList.toggle('open',o);mm.classList.toggle('open',o);hb.setAttribute('aria-expanded',o?'true':'false');mm.setAttribute('aria-hidden',o?'false':'true');document.body.style.overflow=o?'hidden':''}
if(hb&&mm){hb.addEventListener('click',function(){setMenu(!mm.classList.contains('open'))});mm.querySelectorAll('a').forEach(function(a){a.addEventListener('click',function(){setMenu(false)})});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&mm.classList.contains('open'))setMenu(false)})}
var nav=document.getElementById('nav');function onS(){if(nav)nav.classList.toggle('scrolled',window.scrollY>24)}window.addEventListener('scroll',onS,{passive:true});onS();
function load(el){var id=el.getAttribute('data-id');if(window.FDS_NOEMBED){var a=document.createElement('a');a.href='https://www.youtube.com/watch?v='+id;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove();return}if(el.classList.contains('is-playing'))return;var f=document.createElement('iframe');f.src='https://www.youtube-nocookie.com/embed/'+id+'?autoplay=1&rel=0&modestbranding=1&playsinline=1';f.title=el.getAttribute('aria-label')||'Video';f.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';f.allowFullscreen=true;el.appendChild(f);el.classList.add('is-playing')}
document.querySelectorAll('.video[data-id]').forEach(function(v){v.addEventListener('click',function(){load(v)});v.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();load(v)}})});
if('IntersectionObserver' in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){var io=new IntersectionObserver(function(es){es.forEach(function(en){if(en.isIntersecting){en.target.classList.add('in');io.unobserve(en.target)}})},{threshold:0.12,rootMargin:'0px 0px -40px 0px'});document.querySelectorAll('.reveal').forEach(function(el){io.observe(el)})}else{document.querySelectorAll('.reveal').forEach(function(el){el.classList.add('in')})}
var hf=document.querySelector('.hub-filter');if(hf){hf.addEventListener('click',function(e){var b=e.target.closest('button');if(!b)return;hf.querySelectorAll('button').forEach(function(x){x.setAttribute('aria-pressed',x===b?'true':'false')});var f=b.getAttribute('data-f');document.querySelectorAll('#hubcards .acard').forEach(function(c){c.hidden=!!f&&c.getAttribute('data-cat')!==f;c.classList.add('in')})})}
})();
